# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/carrito.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/details.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/login.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/signUp.html"
  to = "/"
  status = 301
